name: Epsilon
main: com.computerdude.epsilon.Main
version: 1.0
commands:
    setlevel:
        description: Set your level
        usage: /setlevel <level> [player]
    getlevel:
        description: Get your level
        usage: /getlevel [player]
