name: Epsilon
main: com.computerdude.epsilon.Epsilon
version: 1.0
commands:
    setlevel:
        description: Set your level
        usage: /setlevel <level> [player]
    getlevel:
        description: Get your level
        usage: /getlevel [player]
    setcoins:
        description: Set your coin balance
        usage: /setcoins <coins> [player]
    getcoins:
        descrption: Get your coin balance
        usage: /getcoins [player]
