name: Epsilon
main: com.epsilon.Epsilon
version: 1.0
authors: [Justin "JustBru00" Brubaker, ComputerDude, __null]
commands:
    setlevel:
        description: Set your level
        usage: /setlevel <level> [player]
    getlevel:
        description: Get your level
        usage: /getlevel [player]
    setcoins:
        description: Set your coin balance
        usage: /setcoins <coins> [player]
    getcoins:
        descrption: Get your coin balance
        usage: /getcoins [player]
    gms:
      description: Sets gamemode to survival. 
      usage: /gms <player>
    gmc:
      description: Sets gamemode to creative.    
      usage: /gmc <player>
    adminmode:
        descrption: Toggles admin mode.
        usage: /adminmode