name: Epsilon
main: com.epsilon.Epsilon
version: 1.0
authors: [ComputerDude, null, JustBru00]
commands:
    setlevel:
        description: Set your level
        usage: /setlevel <level> [player]
    getlevel:
        description: Get your level
        usage: /getlevel [player]
    setcoins:
        description: Set your coin balance
        usage: /setcoins <coins> [player]
    getcoins:
        descrption: Get your coin balance
        usage: /getcoins [player]
    gms:
        description: Set gamemode to survival.
        usage: /gms [player]
    gmc:
        description: Set gamemode to creative.
        usage: /gmc [player]
    gma:
        descrption: Set gamemode to adventure.
        usage: /gma [player]
    adminmode:
        descrption: Toggles admin mode.
        usage: /adminmode
    inventorysee:
        descrption: View a players inventory.
        usage: /inventorysee <player>